### ISSUE TITLE
课程文档

### ISSUE THREAD

**Issue by Ezio6** [Congb19/Scope#1]
学长你可以上传一下创新实践的课程文档吗

**Comment by Congb19** [comment]
> 学长你可以上传一下创新实践的课程文档吗

课程文档是什么

**Comment by Ezio6** [comment]
> > 学长你可以上传一下创新实践的课程文档吗
> 
> 课程文档是什么

期末要交的文档🥺

**Comment by Congb19** [comment]
> > > 学长你可以上传一下创新实践的课程文档吗
> > 
> > 
> > 课程文档是什么
> 
> 期末要交的文档🥺

加我Q347006087私聊吧
